language: node_js
node_js:
- 'node'
env:
  - SERVER_IP_ADDRESS=157.245.40.180

before_install:
- openssl aes-256-cbc -K $encrypted_3c8207afbe2f_key -iv $encrypted_3c8207afbe2f_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
script:
  - bash scripts/test.sh
after_success:
  - bash scripts/deploy.sh
