version: "3"
services:
  frontend:
    container_name: hilfling-frontend
    image: fotogjengen/hilfling-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.hilfling-frontend.entrypoints=web # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-frontend.entrypoints=websecure # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.routers.hilfling-frontend.rule=Host(`fg.nikzy.no`) # <== Your Domain Name goes here for the http rule
      - traefik.http.routers.hilfling-frontend.tls.certresolver=lets-encr # Adds SSL to App

networks:
  traefik:
    external: true
