version: '2'

services:
  intern-nginx:
    environment:
      - PUID=1000
      - PGID=1000
    container_name: intern-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:80'
    networks:
      - traefik
    labels:
      - traefik.port = 80
      - traefik.http.routers.intern-nginx.rule=Host("api.nikzy.no")
      - traefik.http.routers.registry.service=intern-nginx
networks:
  traefik:
    external: true

