version: '2'

services:
  extern-nginx:
    container_name: extern-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - traefik
    labels:
      - traefik.port = 80
      - traefik.http.routers.extern-nginx.rule=Host('fg.carosa.no')
networks:
  traefik:
    external: true

