export const questions: string[] = [
  "👔 Har finest stil?",
  "💳 Kortmisbruker mest?",
  "🕒 Hvem har best dansemoves kl.03:59?",
  "👵 Hvem er mest sannsynlig til å flørte med en gammelpang på h-helg?",
  "👗 Hvem kler seg mest slutty på rocky?",
  "📱 Ville klart seg lengst uten mobil og pc?",
  "🍺 Har høyest toleranse?",
  "❤️ Mest romantisk?",
  "⚰️ Forfalske sin egen død for å se hvem som kommer i begravelsen?",
  "🍱 Kunne spist mest sushi?",
  "💸 Har brukt mest penger på hyblene?",
  "💋 Har klint med flest på hyblene?",
  "💑 Har hatt flest kjærester?",
  "🏝 Kunne du vært på en øde øy med?",
  "🕺 Hvem har mest slengen?",
  "📸 Er mest fotogen?",
  "😎 Er tøffest i trynet?",
  "🏢 Mest sannsynlig til å gå på taket?",
  "🍷 Er først til å søle alkohol under en galla-middag?",
  "🔮 Bli med i en kult?",
  "🥤 Kunne jobbet på joe & the juice?",
  "💘 Dratt på flest tinderdates?",
  "🐟 Minner mest om en monsterkveite?",
  "💁‍♀️ Er mest sassy?",
  "🎵 Setter på den rareste/dårligste musikken på aqua?",
  "🍺 Er best på å chugge?",
  "🗺 Mest sannsynlig til å gå seg bort på hyblene?",
  "🤝 Stiller alltid opp?",
  "🗣 Har finest dialekt?",
  "🏥 Mest sannsynlig til å havne på legevakten?",
  "🛏 Har ligger med flest?",
  "🍖 Mest sannsynlig til å drikke pinnekjøttfettet?",
  "😤 Hvem er mest rude?",
  "😬 Hvem er mest cringe?",
  "💪 Er sterkest?",
  "💝 Ville du spurt om kjærlighetsråd?",
  "🎉 Insjer først på nakenfest?",
  "🍷 Får mest vinkryss?",
  "🦄 Skiller seg mest ut i mengden?",
  "🗣 Er FG-gossip?",
  "📺 Ser på mest reality-drit?",
  "🧪 Er mest sannsynlig til å drikke kjemi?",
  "🎤 Tar over som forsanger på Fotogjengen-sangen?",
  "👑 Blir neste samfundet/uka/isfit-leder?",
  "🎵 Første til å sette på musikk?",
  "😏 Har mest draget?",
  "📸 Er mest sannsynlig til å ta nudes i studio?",
  "⏰ Holder ut lengst på hyblene?",
  "💉 Har tatt tatovering/piercing i fylla?",
  "👶 Hvem får barn først?",
  "🏗 Hvem er mest gira på nybygg?",
  "📔 Hvem ville du helst lest dagboken til?",
  "🔞 Hvem har hatt sex på det rareste stedet?",
  "😈 Hvem er den nye FG-dirty?",
  "🎊 Inviterer på neste skinnefest?",
  "🦸 Flinkest på å berge?",
  "🔮 Tror på synske?",
  "🚬 Røyker mest på Aqua?",
  "😴 Snorker mest?",
  "🎯 Mest sannsynlig til å ta en splittsøker?",
  "🐗 Er mest vill?",
  "🎫 Mister daljene sine først?",
  "🔔 Plinger mest?",
  "🍽 Mest sannsynlig til å spise noe fra gulvet på aqua?",
  "📤 Mest sannsynlig til å laste opp alle bildene på forsiden?",
  "📸 Mest sannsynlig til å «ta med seg noen i mørkerommet»?",
  "🤢 Er mest bakfull på 17.mai?",
  "🤳 Tar flest selfies?",
  "📱 Er alltid på mobilen på møtet?",
  "👨 Ligner mest på Tormod?",
  "🤗 Er best til å trøste fulle folk?",
  "⚖️ Er mest rettferdig?",
  "🤦 Er dårligst på møtetegn?",
  "⏳ Er tregest til å redigere?",
  "🤔 Er mest ubesluttsom?",
  "💦 Utløser sprinkleranlegget ved uhell?",
  "👩 Er mother?",
  "🤱 Er mommy?",
  "🚗 Er den mest aggressive sjåføren?",
  "📝 Er aldri hvit på krysselista?",
  "😴 Mest sannsynlig til å sovne på kapellet?",
  "🍔 Bestiller alltid Nordahls?",
  "🏠 Hvem er mest sannsynlig til å bli med en pirumitt hjem?",
  "🎨 Kunne vært aktmodell?",
  "🤓 Nørder mest?",
  "🌟 Er fg-kjendis?",
  "👣 Mest sannsynlig til å slikke noen mellom tærne?",
  "😂 Er morsomst?",
  "💋 Er den beste til å kysse?",
  "🎂 Baker den beste kaken?",
  "🔞 Har den mest skitne nettleserhistorikken?",
  "🌪 Faller mest på fylla?",
  "🥡 Bestiller mest fra sesam?",
  "🕵️ Er mest mystisk?",
  "🎯 Kunne tatt en tramp-stamp?",
  "🤫 Blir kleptoman på fylla?",
  "🏢 Mest sannsynlig til å shotte fra taket?",
  "🤮 Mest sannsynlig til å spy på snabeldassen?",
  "🍺 Henger mest i Bodegaen?",
  "🥃 Skal chugge eller ta en tequilashot sammen med deg?"
];