export const questions: Record<number, string> = {
  1: "📵 Er alltid på mobilen?",
  2: "💪 Har mest viljestyrke?",
  3: "🍺 Er best på å styrte?",
  4: "🚘 Er dårligst sjåfør?",
  5: "🐗 Er mest vill?",
  6: "💸 Spanderer alltid på fylla?",
  7: "🌊 Er kåtest?",
  8: "🤓 Er flinkest på skolen?",
  9: "🤲 Tar seg mest på puppene?",
  10: "🎅 Trodde lengst på julenissen?",
  11: "⏳ Mest ubesluttsom?",
  12: "🥃 Har høyest toleranse?",
  13: "✌️ Er mest rettferdig?",
  14: "😏 Lager de sjukeste lydene i senga?",
  15: "🎗 Gir mest til veldedighet?",
  16: "🙄 Er mest overlegen?",
  17: "💯 Kommer til å lykkes best i livet?",
  18: "🪂 Er en adrenalin junkie?",
  19: "🏆 Googler seg selv oftest?",
  20: "😇 Er lykkeligst?",
  21: "🕵️‍♀️ Er den verste stalkeren?",
  22: "🎻 Har dårligst musikksmak?",
  23: "🥱 Kommer til og sovne med en pizza i hånden?",
  24: "🚿 Har shava og er forberedt på alt?",
  25: "🎖 Har hatt seg med flest?",
  26: "🏋️‍♀️ Er sterkest?",
  27: "🤮 Kommer mest sannsynlig til å spy i kveld?",
  28: "🗣 Har finest dialekt?",
  29: "🔮 Havner på gata?",
  30: "☀️ Lyser opp rommet?",
  31: "🦄 Skiller seg mest ut i mengden?",
  32: "😎 Har størst kjendisfaktor?",
  33: "🧗‍♂️ Er mest eventyrlysten?",
  34: "👓 Har best syn?",
  35: "💤 Snorker mest?",
  36: "💩 Slipper de verste fisene?",
  37: "🙋‍♂️ Kunne levd best med bare en arm og ett ben?",
  38: "🏃‍♂️ Løper fortest?",
  39: "🤓 Nørder mest?",
  40: "💍 Kommer til å gifte seg først?",
  41: "🛫 Hvem er medlem av Mile High Club?",
  42: "💰 Kommer til å bli rikest?",
  43: "💋 Er den beste til å kysse?",
  44: "🐾 Tar med seg noen hjem i kveld?",
  45: "🌵 Stikker mest?",
  46: "🐎 Rir best?",
  47: "🏡 Bor finest?",
  48: "🥽 Er mest positiv til nye utfordringer?",
  49: "👨 Er en av gutta?",
  50: "📸 Tar flest selfies?",
  51: "🔚 Kommer raskest?",
  52: "🏝 Kunne du vært på en øde øy med?",
  53: "🥶 Har lettest for å bryte isen med noen ukjente?",
  54: "🎓 Kommer mest sannsynlig til å stryke et fag dette semesteret?",
  55: "🚵 Er mest sporty?",
  56: "🔥 Lager best stemning på vors?",
  57: "👀 Har de vakreste øyene?",
  58: "❌ Kommer seg ikke inn på byen i kveld?",
  59: "🛏 Er best i senga?",
  60: "🆘 Er mest drita?",
  61: "🏫 Har best karakterer nå?",
  62: "🎮 Er den svetteste gameren?",
  63: "🐻 Har best sjanse til å overleve mot en bjørn?",
  64: "👓 Kler briller best?",
  65: "🥺 Er snillest?",
  66: "👌 Har hooket med flest?",
  67: "💼 Er mest klar for arbeidslivet?",
  68: "👱‍♀️ Har flest blonde øyeblikk?",
  69: "😡 Har mest temperament?",
  70: "😘 Holder på med flere samtidig?",
  71: "😌 Selv tror den er morsomst?",
  72: "💔 Har hatt flest kjærester?",
  73: "🐭 Er en liten luremus?",
  74: "🎧 Har verst musikksmak?",
  75: "🎭 Har mest humørsvingninger?",
  76: "😵 Synger styggest?",
  77: "💈 Har mest kroppshår?",
  78: "☠️ Er tøffest i trynet?",
  79: "💄 Har finest lepper?",
  80: "🔞 Har den mest skitne nettleserhistorikken?",
  81: "🚇 Er best kjent i byen dere er i?",
  82: "🚑 Hvem har vært flest ganger på legevakten det siste året?",
  83: "💃 Hadde gjort det best på skal vi danse?",
  84: "👨‍👩‍👦 Kunne du aldri hatt med i et familieselskap?",
  85: "🤯 Tåler smerte best?",
  86: "🤣 Driter seg alltid ut?",
  87: "🏆 Er flinkest til å sjekke opp på byen?",
  88: "🚁 Er mest spontan?",
  89: "🔮 Tror på synske?",
  90: "📞 Har kortest telefonsamtaler?",
  91: "💰 Har størst lommebok?",
  92: "🚽 Ser på mest reality-drit?",
  93: "💙 Har tatt kongla flest ganger?",
  94: "🦶 Har størst føtter?",
  95: "🕵️‍♂️ Er mest mystisk?",
  96: "🙊 Minner mest om en ape?",
  97: "💌 Har hatt flest kjønnssjukdommer?",
  98: "🏃 Tar alltid en for laget?",
  99: "😷 Er mest frekk i kjeften?",
  100: "💯 Skal ta bonski sammen med deg?",
};