export const questions: string[] = [
  "📵 Er alltid på mobilen?",
  "💪 Har mest viljestyrke?",
  "🍺 Er best på å styrte?",
  "🚘 Er dårligst sjåfør?",
  "🐗 Er mest vill?",
  "💸 Spanderer alltid på fylla?",
  "🌊 Er kåtest?",
  "🤓 Er flinkest på skolen?",
  "🤲 Tar seg mest på puppene?",
  "🎅 Trodde lengst på julenissen?",
  "⏳ Mest ubesluttsom?",
  "🥃 Har høyest toleranse?",
  "✌️ Er mest rettferdig?",
  "😏 Lager de sjukeste lydene i senga?",
  "🎗 Gir mest til veldedighet?",
  "🙄 Er mest overlegen?",
  "💯 Kommer til å lykkes best i livet?",
  "🪂 Er en adrenalin junkie?",
  "🏆 Googler seg selv oftest?",
  "😇 Er lykkeligst?",
  "🕵️‍♀️ Er den verste stalkeren?",
  "🎻 Har dårligst musikksmak?",
  "🥱 Kommer til og sovne med en pizza i hånden?",
  "🚿 Har shava og er forberedt på alt?",
  "🎖 Har hatt seg med flest?",
  "🏋️‍♀️ Er sterkest?",
  "🤮 Kommer mest sannsynlig til å spy i kveld?",
  "🗣 Har finest dialekt?",
  "🔮 Havner på gata?",
  "☀️ Lyser opp rommet?",
  "🦄 Skiller seg mest ut i mengden?",
  "😎 Har størst kjendisfaktor?",
  "🧗‍♂️ Er mest eventyrlysten?",
  "👓 Har best syn?",
  "💤 Snorker mest?",
  "💩 Slipper de verste fisene?",
  "🙋‍♂️ Kunne levd best med bare en arm og ett ben?",
  "🏃‍♂️ Løper fortest?",
  "🤓 Nørder mest?",
  "💍 Kommer til å gifte seg først?",
  "🛫 Hvem er medlem av Mile High Club?",
  "💰 Kommer til å bli rikest?",
  "💋 Er den beste til å kysse?",
  "🐾 Tar med seg noen hjem i kveld?",
  "🌵 Stikker mest?",
  "🐎 Rir best?",
  "🏡 Bor finest?",
  "🥽 Er mest positiv til nye utfordringer?",
  "👨 Er en av gutta?",
  "📸 Tar flest selfies?",
  "🔚 Kommer raskest?",
  "🏝 Kunne du vært på en øde øy med?",
  "🥶 Har lettest for å bryte isen med noen ukjente?",
  "🎓 Kommer mest sannsynlig til å stryke et fag dette semesteret?",
  "🚵 Er mest sporty?",
  "🔥 Lager best stemning på vors?",
  "👀 Har de vakreste øyene?",
  "❌ Kommer seg ikke inn på byen i kveld?",
  "🛏 Er best i senga?",
  "🆘 Er mest drita?",
  "🏫 Har best karakterer nå?",
  "🎮 Er den svetteste gameren?",
  "🐻 Har best sjanse til å overleve mot en bjørn?",
  "👓 Kler briller best?",
  "🥺 Er snillest?",
  "👌 Har hooket med flest?",
  "💼 Er mest klar for arbeidslivet?",
  "👱‍♀️ Har flest blonde øyeblikk?",
  "😡 Har mest temperament?",
  "😘 Holder på med flere samtidig?",
  "😌 Selv tror den er morsomst?",
  "💔 Har hatt flest kjærester?",
  "🐭 Er en liten luremus?",
  "🎧 Har verst musikksmak?",
  "🎭 Har mest humørsvingninger?",
  "😵 Synger styggest?",
  "💈 Har mest kroppshår?",
  "☠️ Er tøffest i trynet?",
  "💄 Har finest lepper?",
  "🔞 Har den mest skitne nettleserhistorikken?",
  "🚇 Er best kjent i byen dere er i?",
  "🚑 Hvem har vært flest ganger på legevakten det siste året?",
  "💃 Hadde gjort det best på skal vi danse?",
  "👨‍👩‍👦 Kunne du aldri hatt med i et familieselskap?",
  "🤯 Tåler smerte best?",
  "🤣 Driter seg alltid ut?",
  "🏆 Er flinkest til å sjekke opp på byen?",
  "🚁 Er mest spontan?",
  "🔮 Tror på synske?",
  "📞 Har kortest telefonsamtaler?",
  "💰 Har størst lommebok?",
  "🚽 Ser på mest reality-drit?",
  "💙 Har tatt kongla flest ganger?",
  "🦶 Har størst føtter?",
  "🕵️‍♂️ Er mest mystisk?",
  "🙊 Minner mest om en ape?",
  "💌 Har hatt flest kjønnssjukdommer?",
  "🏃 Tar alltid en for laget?",
  "😷 Er mest frekk i kjeften?",
  "💯 Skal ta bonski sammen med deg?",
];