/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as FgAuthenticatedRouteRouteImport } from './routes/_fgAuthenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as MotiveMotiveIdRouteImport } from './routes/motive.$motiveId'
import { Route as AboutInfoRouteImport } from './routes/about/info'
import { Route as AboutHistoryRouteImport } from './routes/about/history'
import { Route as FgAuthenticatedFgIndexRouteImport } from './routes/_fgAuthenticated/fg/index'
import { Route as FgAuthenticatedFgUploadRouteImport } from './routes/_fgAuthenticated/fg/upload'
import { Route as FgAuthenticatedFgProfileRouteImport } from './routes/_fgAuthenticated/fg/profile'
import { Route as FgAuthenticatedFgProjectsIndexRouteImport } from './routes/_fgAuthenticated/fg/projects/index'
import { Route as FgAuthenticatedFgArchiveBossIndexRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/index'
import { Route as FgAuthenticatedFgProjectsKull26IndexRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/index'
import { Route as FgAuthenticatedFgProjectsKull26ThirdgameRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/thirdgame'
import { Route as FgAuthenticatedFgProjectsKull26SecondgameRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/secondgame'
import { Route as FgAuthenticatedFgProjectsKull26FirstgameRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/firstgame'
import { Route as FgAuthenticatedFgArchiveBossEditUserUserIdRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/editUser.$userId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FgAuthenticatedRouteRoute = FgAuthenticatedRouteRouteImport.update({
  id: '/_fgAuthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const MotiveMotiveIdRoute = MotiveMotiveIdRouteImport.update({
  id: '/motive/$motiveId',
  path: '/motive/$motiveId',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutInfoRoute = AboutInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AboutRouteRoute,
} as any)
const FgAuthenticatedFgIndexRoute = FgAuthenticatedFgIndexRouteImport.update({
  id: '/fg/',
  path: '/fg/',
  getParentRoute: () => FgAuthenticatedRouteRoute,
} as any)
const FgAuthenticatedFgUploadRoute = FgAuthenticatedFgUploadRouteImport.update({
  id: '/fg/upload',
  path: '/fg/upload',
  getParentRoute: () => FgAuthenticatedRouteRoute,
} as any)
const FgAuthenticatedFgProfileRoute =
  FgAuthenticatedFgProfileRouteImport.update({
    id: '/fg/profile',
    path: '/fg/profile',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsIndexRoute =
  FgAuthenticatedFgProjectsIndexRouteImport.update({
    id: '/fg/projects/',
    path: '/fg/projects/',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossIndexRoute =
  FgAuthenticatedFgArchiveBossIndexRouteImport.update({
    id: '/fg/archiveBoss/',
    path: '/fg/archiveBoss/',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26IndexRoute =
  FgAuthenticatedFgProjectsKull26IndexRouteImport.update({
    id: '/fg/projects/kull26/',
    path: '/fg/projects/kull26/',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26ThirdgameRoute =
  FgAuthenticatedFgProjectsKull26ThirdgameRouteImport.update({
    id: '/fg/projects/kull26/thirdgame',
    path: '/fg/projects/kull26/thirdgame',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26SecondgameRoute =
  FgAuthenticatedFgProjectsKull26SecondgameRouteImport.update({
    id: '/fg/projects/kull26/secondgame',
    path: '/fg/projects/kull26/secondgame',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26FirstgameRoute =
  FgAuthenticatedFgProjectsKull26FirstgameRouteImport.update({
    id: '/fg/projects/kull26/firstgame',
    path: '/fg/projects/kull26/firstgame',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossEditUserUserIdRoute =
  FgAuthenticatedFgArchiveBossEditUserUserIdRouteImport.update({
    id: '/fg/archiveBoss/editUser/$userId',
    path: '/fg/archiveBoss/editUser/$userId',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/search': typeof SearchRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/info': typeof AboutInfoRoute
  '/motive/$motiveId': typeof MotiveMotiveIdRoute
  '/about/': typeof AboutIndexRoute
  '/fg/profile': typeof FgAuthenticatedFgProfileRoute
  '/fg/upload': typeof FgAuthenticatedFgUploadRoute
  '/fg/': typeof FgAuthenticatedFgIndexRoute
  '/fg/archiveBoss/': typeof FgAuthenticatedFgArchiveBossIndexRoute
  '/fg/projects/': typeof FgAuthenticatedFgProjectsIndexRoute
  '/fg/archiveBoss/editUser/$userId': typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
  '/fg/projects/kull26/firstgame': typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  '/fg/projects/kull26/secondgame': typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  '/fg/projects/kull26/thirdgame': typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  '/fg/projects/kull26/': typeof FgAuthenticatedFgProjectsKull26IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/search': typeof SearchRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/info': typeof AboutInfoRoute
  '/motive/$motiveId': typeof MotiveMotiveIdRoute
  '/about': typeof AboutIndexRoute
  '/fg/profile': typeof FgAuthenticatedFgProfileRoute
  '/fg/upload': typeof FgAuthenticatedFgUploadRoute
  '/fg': typeof FgAuthenticatedFgIndexRoute
  '/fg/archiveBoss': typeof FgAuthenticatedFgArchiveBossIndexRoute
  '/fg/projects': typeof FgAuthenticatedFgProjectsIndexRoute
  '/fg/archiveBoss/editUser/$userId': typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
  '/fg/projects/kull26/firstgame': typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  '/fg/projects/kull26/secondgame': typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  '/fg/projects/kull26/thirdgame': typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  '/fg/projects/kull26': typeof FgAuthenticatedFgProjectsKull26IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_fgAuthenticated': typeof FgAuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/search': typeof SearchRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/info': typeof AboutInfoRoute
  '/motive/$motiveId': typeof MotiveMotiveIdRoute
  '/about/': typeof AboutIndexRoute
  '/_fgAuthenticated/fg/profile': typeof FgAuthenticatedFgProfileRoute
  '/_fgAuthenticated/fg/upload': typeof FgAuthenticatedFgUploadRoute
  '/_fgAuthenticated/fg/': typeof FgAuthenticatedFgIndexRoute
  '/_fgAuthenticated/fg/archiveBoss/': typeof FgAuthenticatedFgArchiveBossIndexRoute
  '/_fgAuthenticated/fg/projects/': typeof FgAuthenticatedFgProjectsIndexRoute
  '/_fgAuthenticated/fg/archiveBoss/editUser/$userId': typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
  '/_fgAuthenticated/fg/projects/kull26/firstgame': typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  '/_fgAuthenticated/fg/projects/kull26/secondgame': typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  '/_fgAuthenticated/fg/projects/kull26/thirdgame': typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  '/_fgAuthenticated/fg/projects/kull26/': typeof FgAuthenticatedFgProjectsKull26IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/photos'
    | '/search'
    | '/about/history'
    | '/about/info'
    | '/motive/$motiveId'
    | '/about/'
    | '/fg/profile'
    | '/fg/upload'
    | '/fg/'
    | '/fg/archiveBoss/'
    | '/fg/projects/'
    | '/fg/archiveBoss/editUser/$userId'
    | '/fg/projects/kull26/firstgame'
    | '/fg/projects/kull26/secondgame'
    | '/fg/projects/kull26/thirdgame'
    | '/fg/projects/kull26/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/photos'
    | '/search'
    | '/about/history'
    | '/about/info'
    | '/motive/$motiveId'
    | '/about'
    | '/fg/profile'
    | '/fg/upload'
    | '/fg'
    | '/fg/archiveBoss'
    | '/fg/projects'
    | '/fg/archiveBoss/editUser/$userId'
    | '/fg/projects/kull26/firstgame'
    | '/fg/projects/kull26/secondgame'
    | '/fg/projects/kull26/thirdgame'
    | '/fg/projects/kull26'
  id:
    | '__root__'
    | '/'
    | '/_fgAuthenticated'
    | '/about'
    | '/login'
    | '/photos'
    | '/search'
    | '/about/history'
    | '/about/info'
    | '/motive/$motiveId'
    | '/about/'
    | '/_fgAuthenticated/fg/profile'
    | '/_fgAuthenticated/fg/upload'
    | '/_fgAuthenticated/fg/'
    | '/_fgAuthenticated/fg/archiveBoss/'
    | '/_fgAuthenticated/fg/projects/'
    | '/_fgAuthenticated/fg/archiveBoss/editUser/$userId'
    | '/_fgAuthenticated/fg/projects/kull26/firstgame'
    | '/_fgAuthenticated/fg/projects/kull26/secondgame'
    | '/_fgAuthenticated/fg/projects/kull26/thirdgame'
    | '/_fgAuthenticated/fg/projects/kull26/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FgAuthenticatedRouteRoute: typeof FgAuthenticatedRouteRouteWithChildren
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PhotosRoute: typeof PhotosRoute
  SearchRoute: typeof SearchRoute
  MotiveMotiveIdRoute: typeof MotiveMotiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_fgAuthenticated': {
      id: '/_fgAuthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FgAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/motive/$motiveId': {
      id: '/motive/$motiveId'
      path: '/motive/$motiveId'
      fullPath: '/motive/$motiveId'
      preLoaderRoute: typeof MotiveMotiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/info': {
      id: '/about/info'
      path: '/info'
      fullPath: '/about/info'
      preLoaderRoute: typeof AboutInfoRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/history': {
      id: '/about/history'
      path: '/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/_fgAuthenticated/fg/': {
      id: '/_fgAuthenticated/fg/'
      path: '/fg'
      fullPath: '/fg/'
      preLoaderRoute: typeof FgAuthenticatedFgIndexRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/upload': {
      id: '/_fgAuthenticated/fg/upload'
      path: '/fg/upload'
      fullPath: '/fg/upload'
      preLoaderRoute: typeof FgAuthenticatedFgUploadRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/profile': {
      id: '/_fgAuthenticated/fg/profile'
      path: '/fg/profile'
      fullPath: '/fg/profile'
      preLoaderRoute: typeof FgAuthenticatedFgProfileRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/': {
      id: '/_fgAuthenticated/fg/projects/'
      path: '/fg/projects'
      fullPath: '/fg/projects/'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsIndexRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/': {
      id: '/_fgAuthenticated/fg/archiveBoss/'
      path: '/fg/archiveBoss'
      fullPath: '/fg/archiveBoss/'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossIndexRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/': {
      id: '/_fgAuthenticated/fg/projects/kull26/'
      path: '/fg/projects/kull26'
      fullPath: '/fg/projects/kull26/'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26IndexRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/thirdgame': {
      id: '/_fgAuthenticated/fg/projects/kull26/thirdgame'
      path: '/fg/projects/kull26/thirdgame'
      fullPath: '/fg/projects/kull26/thirdgame'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26ThirdgameRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/secondgame': {
      id: '/_fgAuthenticated/fg/projects/kull26/secondgame'
      path: '/fg/projects/kull26/secondgame'
      fullPath: '/fg/projects/kull26/secondgame'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26SecondgameRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/firstgame': {
      id: '/_fgAuthenticated/fg/projects/kull26/firstgame'
      path: '/fg/projects/kull26/firstgame'
      fullPath: '/fg/projects/kull26/firstgame'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26FirstgameRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/editUser/$userId': {
      id: '/_fgAuthenticated/fg/archiveBoss/editUser/$userId'
      path: '/fg/archiveBoss/editUser/$userId'
      fullPath: '/fg/archiveBoss/editUser/$userId'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossEditUserUserIdRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
  }
}

interface FgAuthenticatedRouteRouteChildren {
  FgAuthenticatedFgProfileRoute: typeof FgAuthenticatedFgProfileRoute
  FgAuthenticatedFgUploadRoute: typeof FgAuthenticatedFgUploadRoute
  FgAuthenticatedFgIndexRoute: typeof FgAuthenticatedFgIndexRoute
  FgAuthenticatedFgArchiveBossIndexRoute: typeof FgAuthenticatedFgArchiveBossIndexRoute
  FgAuthenticatedFgProjectsIndexRoute: typeof FgAuthenticatedFgProjectsIndexRoute
  FgAuthenticatedFgArchiveBossEditUserUserIdRoute: typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
  FgAuthenticatedFgProjectsKull26FirstgameRoute: typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  FgAuthenticatedFgProjectsKull26SecondgameRoute: typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  FgAuthenticatedFgProjectsKull26ThirdgameRoute: typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  FgAuthenticatedFgProjectsKull26IndexRoute: typeof FgAuthenticatedFgProjectsKull26IndexRoute
}

const FgAuthenticatedRouteRouteChildren: FgAuthenticatedRouteRouteChildren = {
  FgAuthenticatedFgProfileRoute: FgAuthenticatedFgProfileRoute,
  FgAuthenticatedFgUploadRoute: FgAuthenticatedFgUploadRoute,
  FgAuthenticatedFgIndexRoute: FgAuthenticatedFgIndexRoute,
  FgAuthenticatedFgArchiveBossIndexRoute:
    FgAuthenticatedFgArchiveBossIndexRoute,
  FgAuthenticatedFgProjectsIndexRoute: FgAuthenticatedFgProjectsIndexRoute,
  FgAuthenticatedFgArchiveBossEditUserUserIdRoute:
    FgAuthenticatedFgArchiveBossEditUserUserIdRoute,
  FgAuthenticatedFgProjectsKull26FirstgameRoute:
    FgAuthenticatedFgProjectsKull26FirstgameRoute,
  FgAuthenticatedFgProjectsKull26SecondgameRoute:
    FgAuthenticatedFgProjectsKull26SecondgameRoute,
  FgAuthenticatedFgProjectsKull26ThirdgameRoute:
    FgAuthenticatedFgProjectsKull26ThirdgameRoute,
  FgAuthenticatedFgProjectsKull26IndexRoute:
    FgAuthenticatedFgProjectsKull26IndexRoute,
}

const FgAuthenticatedRouteRouteWithChildren =
  FgAuthenticatedRouteRoute._addFileChildren(FgAuthenticatedRouteRouteChildren)

interface AboutRouteRouteChildren {
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutInfoRoute: typeof AboutInfoRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutHistoryRoute: AboutHistoryRoute,
  AboutInfoRoute: AboutInfoRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FgAuthenticatedRouteRoute: FgAuthenticatedRouteRouteWithChildren,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PhotosRoute: PhotosRoute,
  SearchRoute: SearchRoute,
  MotiveMotiveIdRoute: MotiveMotiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
