/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OmOssRouteRouteImport } from './routes/om-oss/route'
import { Route as FgAuthenticatedRouteRouteImport } from './routes/_fgAuthenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OmOssIndexRouteImport } from './routes/om-oss/index'
import { Route as OmOssBrukAvBilderRouteImport } from './routes/om-oss/bruk-av-bilder'
import { Route as OmOssBestillingRouteImport } from './routes/om-oss/bestilling'
import { Route as MotiveMotiveIdRouteImport } from './routes/motive.$motiveId'
import { Route as FgAuthenticatedFgIndexRouteImport } from './routes/_fgAuthenticated/fg/index'
import { Route as FgAuthenticatedFgUploadRouteImport } from './routes/_fgAuthenticated/fg/upload'
import { Route as FgAuthenticatedFgProfileRouteImport } from './routes/_fgAuthenticated/fg/profile'
import { Route as FgAuthenticatedFgArchiveBossRouteRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/route'
import { Route as FgAuthenticatedFgProjectsIndexRouteImport } from './routes/_fgAuthenticated/fg/projects/index'
import { Route as FgAuthenticatedFgArchiveBossIndexRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/index'
import { Route as FgAuthenticatedFgArchiveBossUsersRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/users'
import { Route as FgAuthenticatedFgArchiveBossPlacesRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/places'
import { Route as FgAuthenticatedFgArchiveBossCategoriesRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/categories'
import { Route as FgAuthenticatedFgArchiveBossAlbumsRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/albums'
import { Route as FgAuthenticatedFgProjectsKull26IndexRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/index'
import { Route as FgAuthenticatedFgProjectsKull26ThirdgameRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/thirdgame'
import { Route as FgAuthenticatedFgProjectsKull26SecondgameRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/secondgame'
import { Route as FgAuthenticatedFgProjectsKull26FirstgameRouteImport } from './routes/_fgAuthenticated/fg/projects/kull26/firstgame'
import { Route as FgAuthenticatedFgArchiveBossEditUserUserIdRouteImport } from './routes/_fgAuthenticated/fg/archiveBoss/editUser.$userId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRouteRoute = OmOssRouteRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const FgAuthenticatedRouteRoute = FgAuthenticatedRouteRouteImport.update({
  id: '/_fgAuthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssIndexRoute = OmOssIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OmOssRouteRoute,
} as any)
const OmOssBrukAvBilderRoute = OmOssBrukAvBilderRouteImport.update({
  id: '/bruk-av-bilder',
  path: '/bruk-av-bilder',
  getParentRoute: () => OmOssRouteRoute,
} as any)
const OmOssBestillingRoute = OmOssBestillingRouteImport.update({
  id: '/bestilling',
  path: '/bestilling',
  getParentRoute: () => OmOssRouteRoute,
} as any)
const MotiveMotiveIdRoute = MotiveMotiveIdRouteImport.update({
  id: '/motive/$motiveId',
  path: '/motive/$motiveId',
  getParentRoute: () => rootRouteImport,
} as any)
const FgAuthenticatedFgIndexRoute = FgAuthenticatedFgIndexRouteImport.update({
  id: '/fg/',
  path: '/fg/',
  getParentRoute: () => FgAuthenticatedRouteRoute,
} as any)
const FgAuthenticatedFgUploadRoute = FgAuthenticatedFgUploadRouteImport.update({
  id: '/fg/upload',
  path: '/fg/upload',
  getParentRoute: () => FgAuthenticatedRouteRoute,
} as any)
const FgAuthenticatedFgProfileRoute =
  FgAuthenticatedFgProfileRouteImport.update({
    id: '/fg/profile',
    path: '/fg/profile',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossRouteRoute =
  FgAuthenticatedFgArchiveBossRouteRouteImport.update({
    id: '/fg/archiveBoss',
    path: '/fg/archiveBoss',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsIndexRoute =
  FgAuthenticatedFgProjectsIndexRouteImport.update({
    id: '/fg/projects/',
    path: '/fg/projects/',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossIndexRoute =
  FgAuthenticatedFgArchiveBossIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => FgAuthenticatedFgArchiveBossRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossUsersRoute =
  FgAuthenticatedFgArchiveBossUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => FgAuthenticatedFgArchiveBossRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossPlacesRoute =
  FgAuthenticatedFgArchiveBossPlacesRouteImport.update({
    id: '/places',
    path: '/places',
    getParentRoute: () => FgAuthenticatedFgArchiveBossRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossCategoriesRoute =
  FgAuthenticatedFgArchiveBossCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => FgAuthenticatedFgArchiveBossRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossAlbumsRoute =
  FgAuthenticatedFgArchiveBossAlbumsRouteImport.update({
    id: '/albums',
    path: '/albums',
    getParentRoute: () => FgAuthenticatedFgArchiveBossRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26IndexRoute =
  FgAuthenticatedFgProjectsKull26IndexRouteImport.update({
    id: '/fg/projects/kull26/',
    path: '/fg/projects/kull26/',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26ThirdgameRoute =
  FgAuthenticatedFgProjectsKull26ThirdgameRouteImport.update({
    id: '/fg/projects/kull26/thirdgame',
    path: '/fg/projects/kull26/thirdgame',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26SecondgameRoute =
  FgAuthenticatedFgProjectsKull26SecondgameRouteImport.update({
    id: '/fg/projects/kull26/secondgame',
    path: '/fg/projects/kull26/secondgame',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgProjectsKull26FirstgameRoute =
  FgAuthenticatedFgProjectsKull26FirstgameRouteImport.update({
    id: '/fg/projects/kull26/firstgame',
    path: '/fg/projects/kull26/firstgame',
    getParentRoute: () => FgAuthenticatedRouteRoute,
  } as any)
const FgAuthenticatedFgArchiveBossEditUserUserIdRoute =
  FgAuthenticatedFgArchiveBossEditUserUserIdRouteImport.update({
    id: '/editUser/$userId',
    path: '/editUser/$userId',
    getParentRoute: () => FgAuthenticatedFgArchiveBossRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/om-oss': typeof OmOssRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/motive/$motiveId': typeof MotiveMotiveIdRoute
  '/om-oss/bestilling': typeof OmOssBestillingRoute
  '/om-oss/bruk-av-bilder': typeof OmOssBrukAvBilderRoute
  '/om-oss/': typeof OmOssIndexRoute
  '/fg/archiveBoss': typeof FgAuthenticatedFgArchiveBossRouteRouteWithChildren
  '/fg/profile': typeof FgAuthenticatedFgProfileRoute
  '/fg/upload': typeof FgAuthenticatedFgUploadRoute
  '/fg/': typeof FgAuthenticatedFgIndexRoute
  '/fg/archiveBoss/albums': typeof FgAuthenticatedFgArchiveBossAlbumsRoute
  '/fg/archiveBoss/categories': typeof FgAuthenticatedFgArchiveBossCategoriesRoute
  '/fg/archiveBoss/places': typeof FgAuthenticatedFgArchiveBossPlacesRoute
  '/fg/archiveBoss/users': typeof FgAuthenticatedFgArchiveBossUsersRoute
  '/fg/archiveBoss/': typeof FgAuthenticatedFgArchiveBossIndexRoute
  '/fg/projects/': typeof FgAuthenticatedFgProjectsIndexRoute
  '/fg/archiveBoss/editUser/$userId': typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
  '/fg/projects/kull26/firstgame': typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  '/fg/projects/kull26/secondgame': typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  '/fg/projects/kull26/thirdgame': typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  '/fg/projects/kull26/': typeof FgAuthenticatedFgProjectsKull26IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/motive/$motiveId': typeof MotiveMotiveIdRoute
  '/om-oss/bestilling': typeof OmOssBestillingRoute
  '/om-oss/bruk-av-bilder': typeof OmOssBrukAvBilderRoute
  '/om-oss': typeof OmOssIndexRoute
  '/fg/profile': typeof FgAuthenticatedFgProfileRoute
  '/fg/upload': typeof FgAuthenticatedFgUploadRoute
  '/fg': typeof FgAuthenticatedFgIndexRoute
  '/fg/archiveBoss/albums': typeof FgAuthenticatedFgArchiveBossAlbumsRoute
  '/fg/archiveBoss/categories': typeof FgAuthenticatedFgArchiveBossCategoriesRoute
  '/fg/archiveBoss/places': typeof FgAuthenticatedFgArchiveBossPlacesRoute
  '/fg/archiveBoss/users': typeof FgAuthenticatedFgArchiveBossUsersRoute
  '/fg/archiveBoss': typeof FgAuthenticatedFgArchiveBossIndexRoute
  '/fg/projects': typeof FgAuthenticatedFgProjectsIndexRoute
  '/fg/archiveBoss/editUser/$userId': typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
  '/fg/projects/kull26/firstgame': typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  '/fg/projects/kull26/secondgame': typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  '/fg/projects/kull26/thirdgame': typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  '/fg/projects/kull26': typeof FgAuthenticatedFgProjectsKull26IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_fgAuthenticated': typeof FgAuthenticatedRouteRouteWithChildren
  '/om-oss': typeof OmOssRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/motive/$motiveId': typeof MotiveMotiveIdRoute
  '/om-oss/bestilling': typeof OmOssBestillingRoute
  '/om-oss/bruk-av-bilder': typeof OmOssBrukAvBilderRoute
  '/om-oss/': typeof OmOssIndexRoute
  '/_fgAuthenticated/fg/archiveBoss': typeof FgAuthenticatedFgArchiveBossRouteRouteWithChildren
  '/_fgAuthenticated/fg/profile': typeof FgAuthenticatedFgProfileRoute
  '/_fgAuthenticated/fg/upload': typeof FgAuthenticatedFgUploadRoute
  '/_fgAuthenticated/fg/': typeof FgAuthenticatedFgIndexRoute
  '/_fgAuthenticated/fg/archiveBoss/albums': typeof FgAuthenticatedFgArchiveBossAlbumsRoute
  '/_fgAuthenticated/fg/archiveBoss/categories': typeof FgAuthenticatedFgArchiveBossCategoriesRoute
  '/_fgAuthenticated/fg/archiveBoss/places': typeof FgAuthenticatedFgArchiveBossPlacesRoute
  '/_fgAuthenticated/fg/archiveBoss/users': typeof FgAuthenticatedFgArchiveBossUsersRoute
  '/_fgAuthenticated/fg/archiveBoss/': typeof FgAuthenticatedFgArchiveBossIndexRoute
  '/_fgAuthenticated/fg/projects/': typeof FgAuthenticatedFgProjectsIndexRoute
  '/_fgAuthenticated/fg/archiveBoss/editUser/$userId': typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
  '/_fgAuthenticated/fg/projects/kull26/firstgame': typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  '/_fgAuthenticated/fg/projects/kull26/secondgame': typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  '/_fgAuthenticated/fg/projects/kull26/thirdgame': typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  '/_fgAuthenticated/fg/projects/kull26/': typeof FgAuthenticatedFgProjectsKull26IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/om-oss'
    | '/login'
    | '/search'
    | '/motive/$motiveId'
    | '/om-oss/bestilling'
    | '/om-oss/bruk-av-bilder'
    | '/om-oss/'
    | '/fg/archiveBoss'
    | '/fg/profile'
    | '/fg/upload'
    | '/fg/'
    | '/fg/archiveBoss/albums'
    | '/fg/archiveBoss/categories'
    | '/fg/archiveBoss/places'
    | '/fg/archiveBoss/users'
    | '/fg/archiveBoss/'
    | '/fg/projects/'
    | '/fg/archiveBoss/editUser/$userId'
    | '/fg/projects/kull26/firstgame'
    | '/fg/projects/kull26/secondgame'
    | '/fg/projects/kull26/thirdgame'
    | '/fg/projects/kull26/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/motive/$motiveId'
    | '/om-oss/bestilling'
    | '/om-oss/bruk-av-bilder'
    | '/om-oss'
    | '/fg/profile'
    | '/fg/upload'
    | '/fg'
    | '/fg/archiveBoss/albums'
    | '/fg/archiveBoss/categories'
    | '/fg/archiveBoss/places'
    | '/fg/archiveBoss/users'
    | '/fg/archiveBoss'
    | '/fg/projects'
    | '/fg/archiveBoss/editUser/$userId'
    | '/fg/projects/kull26/firstgame'
    | '/fg/projects/kull26/secondgame'
    | '/fg/projects/kull26/thirdgame'
    | '/fg/projects/kull26'
  id:
    | '__root__'
    | '/'
    | '/_fgAuthenticated'
    | '/om-oss'
    | '/login'
    | '/search'
    | '/motive/$motiveId'
    | '/om-oss/bestilling'
    | '/om-oss/bruk-av-bilder'
    | '/om-oss/'
    | '/_fgAuthenticated/fg/archiveBoss'
    | '/_fgAuthenticated/fg/profile'
    | '/_fgAuthenticated/fg/upload'
    | '/_fgAuthenticated/fg/'
    | '/_fgAuthenticated/fg/archiveBoss/albums'
    | '/_fgAuthenticated/fg/archiveBoss/categories'
    | '/_fgAuthenticated/fg/archiveBoss/places'
    | '/_fgAuthenticated/fg/archiveBoss/users'
    | '/_fgAuthenticated/fg/archiveBoss/'
    | '/_fgAuthenticated/fg/projects/'
    | '/_fgAuthenticated/fg/archiveBoss/editUser/$userId'
    | '/_fgAuthenticated/fg/projects/kull26/firstgame'
    | '/_fgAuthenticated/fg/projects/kull26/secondgame'
    | '/_fgAuthenticated/fg/projects/kull26/thirdgame'
    | '/_fgAuthenticated/fg/projects/kull26/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FgAuthenticatedRouteRoute: typeof FgAuthenticatedRouteRouteWithChildren
  OmOssRouteRoute: typeof OmOssRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  MotiveMotiveIdRoute: typeof MotiveMotiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_fgAuthenticated': {
      id: '/_fgAuthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FgAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss/': {
      id: '/om-oss/'
      path: '/'
      fullPath: '/om-oss/'
      preLoaderRoute: typeof OmOssIndexRouteImport
      parentRoute: typeof OmOssRouteRoute
    }
    '/om-oss/bruk-av-bilder': {
      id: '/om-oss/bruk-av-bilder'
      path: '/bruk-av-bilder'
      fullPath: '/om-oss/bruk-av-bilder'
      preLoaderRoute: typeof OmOssBrukAvBilderRouteImport
      parentRoute: typeof OmOssRouteRoute
    }
    '/om-oss/bestilling': {
      id: '/om-oss/bestilling'
      path: '/bestilling'
      fullPath: '/om-oss/bestilling'
      preLoaderRoute: typeof OmOssBestillingRouteImport
      parentRoute: typeof OmOssRouteRoute
    }
    '/motive/$motiveId': {
      id: '/motive/$motiveId'
      path: '/motive/$motiveId'
      fullPath: '/motive/$motiveId'
      preLoaderRoute: typeof MotiveMotiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_fgAuthenticated/fg/': {
      id: '/_fgAuthenticated/fg/'
      path: '/fg'
      fullPath: '/fg/'
      preLoaderRoute: typeof FgAuthenticatedFgIndexRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/upload': {
      id: '/_fgAuthenticated/fg/upload'
      path: '/fg/upload'
      fullPath: '/fg/upload'
      preLoaderRoute: typeof FgAuthenticatedFgUploadRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/profile': {
      id: '/_fgAuthenticated/fg/profile'
      path: '/fg/profile'
      fullPath: '/fg/profile'
      preLoaderRoute: typeof FgAuthenticatedFgProfileRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss': {
      id: '/_fgAuthenticated/fg/archiveBoss'
      path: '/fg/archiveBoss'
      fullPath: '/fg/archiveBoss'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossRouteRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/': {
      id: '/_fgAuthenticated/fg/projects/'
      path: '/fg/projects'
      fullPath: '/fg/projects/'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsIndexRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/': {
      id: '/_fgAuthenticated/fg/archiveBoss/'
      path: '/'
      fullPath: '/fg/archiveBoss/'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossIndexRouteImport
      parentRoute: typeof FgAuthenticatedFgArchiveBossRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/users': {
      id: '/_fgAuthenticated/fg/archiveBoss/users'
      path: '/users'
      fullPath: '/fg/archiveBoss/users'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossUsersRouteImport
      parentRoute: typeof FgAuthenticatedFgArchiveBossRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/places': {
      id: '/_fgAuthenticated/fg/archiveBoss/places'
      path: '/places'
      fullPath: '/fg/archiveBoss/places'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossPlacesRouteImport
      parentRoute: typeof FgAuthenticatedFgArchiveBossRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/categories': {
      id: '/_fgAuthenticated/fg/archiveBoss/categories'
      path: '/categories'
      fullPath: '/fg/archiveBoss/categories'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossCategoriesRouteImport
      parentRoute: typeof FgAuthenticatedFgArchiveBossRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/albums': {
      id: '/_fgAuthenticated/fg/archiveBoss/albums'
      path: '/albums'
      fullPath: '/fg/archiveBoss/albums'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossAlbumsRouteImport
      parentRoute: typeof FgAuthenticatedFgArchiveBossRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/': {
      id: '/_fgAuthenticated/fg/projects/kull26/'
      path: '/fg/projects/kull26'
      fullPath: '/fg/projects/kull26/'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26IndexRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/thirdgame': {
      id: '/_fgAuthenticated/fg/projects/kull26/thirdgame'
      path: '/fg/projects/kull26/thirdgame'
      fullPath: '/fg/projects/kull26/thirdgame'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26ThirdgameRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/secondgame': {
      id: '/_fgAuthenticated/fg/projects/kull26/secondgame'
      path: '/fg/projects/kull26/secondgame'
      fullPath: '/fg/projects/kull26/secondgame'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26SecondgameRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/projects/kull26/firstgame': {
      id: '/_fgAuthenticated/fg/projects/kull26/firstgame'
      path: '/fg/projects/kull26/firstgame'
      fullPath: '/fg/projects/kull26/firstgame'
      preLoaderRoute: typeof FgAuthenticatedFgProjectsKull26FirstgameRouteImport
      parentRoute: typeof FgAuthenticatedRouteRoute
    }
    '/_fgAuthenticated/fg/archiveBoss/editUser/$userId': {
      id: '/_fgAuthenticated/fg/archiveBoss/editUser/$userId'
      path: '/editUser/$userId'
      fullPath: '/fg/archiveBoss/editUser/$userId'
      preLoaderRoute: typeof FgAuthenticatedFgArchiveBossEditUserUserIdRouteImport
      parentRoute: typeof FgAuthenticatedFgArchiveBossRouteRoute
    }
  }
}

interface FgAuthenticatedFgArchiveBossRouteRouteChildren {
  FgAuthenticatedFgArchiveBossAlbumsRoute: typeof FgAuthenticatedFgArchiveBossAlbumsRoute
  FgAuthenticatedFgArchiveBossCategoriesRoute: typeof FgAuthenticatedFgArchiveBossCategoriesRoute
  FgAuthenticatedFgArchiveBossPlacesRoute: typeof FgAuthenticatedFgArchiveBossPlacesRoute
  FgAuthenticatedFgArchiveBossUsersRoute: typeof FgAuthenticatedFgArchiveBossUsersRoute
  FgAuthenticatedFgArchiveBossIndexRoute: typeof FgAuthenticatedFgArchiveBossIndexRoute
  FgAuthenticatedFgArchiveBossEditUserUserIdRoute: typeof FgAuthenticatedFgArchiveBossEditUserUserIdRoute
}

const FgAuthenticatedFgArchiveBossRouteRouteChildren: FgAuthenticatedFgArchiveBossRouteRouteChildren =
  {
    FgAuthenticatedFgArchiveBossAlbumsRoute:
      FgAuthenticatedFgArchiveBossAlbumsRoute,
    FgAuthenticatedFgArchiveBossCategoriesRoute:
      FgAuthenticatedFgArchiveBossCategoriesRoute,
    FgAuthenticatedFgArchiveBossPlacesRoute:
      FgAuthenticatedFgArchiveBossPlacesRoute,
    FgAuthenticatedFgArchiveBossUsersRoute:
      FgAuthenticatedFgArchiveBossUsersRoute,
    FgAuthenticatedFgArchiveBossIndexRoute:
      FgAuthenticatedFgArchiveBossIndexRoute,
    FgAuthenticatedFgArchiveBossEditUserUserIdRoute:
      FgAuthenticatedFgArchiveBossEditUserUserIdRoute,
  }

const FgAuthenticatedFgArchiveBossRouteRouteWithChildren =
  FgAuthenticatedFgArchiveBossRouteRoute._addFileChildren(
    FgAuthenticatedFgArchiveBossRouteRouteChildren,
  )

interface FgAuthenticatedRouteRouteChildren {
  FgAuthenticatedFgArchiveBossRouteRoute: typeof FgAuthenticatedFgArchiveBossRouteRouteWithChildren
  FgAuthenticatedFgProfileRoute: typeof FgAuthenticatedFgProfileRoute
  FgAuthenticatedFgUploadRoute: typeof FgAuthenticatedFgUploadRoute
  FgAuthenticatedFgIndexRoute: typeof FgAuthenticatedFgIndexRoute
  FgAuthenticatedFgProjectsIndexRoute: typeof FgAuthenticatedFgProjectsIndexRoute
  FgAuthenticatedFgProjectsKull26FirstgameRoute: typeof FgAuthenticatedFgProjectsKull26FirstgameRoute
  FgAuthenticatedFgProjectsKull26SecondgameRoute: typeof FgAuthenticatedFgProjectsKull26SecondgameRoute
  FgAuthenticatedFgProjectsKull26ThirdgameRoute: typeof FgAuthenticatedFgProjectsKull26ThirdgameRoute
  FgAuthenticatedFgProjectsKull26IndexRoute: typeof FgAuthenticatedFgProjectsKull26IndexRoute
}

const FgAuthenticatedRouteRouteChildren: FgAuthenticatedRouteRouteChildren = {
  FgAuthenticatedFgArchiveBossRouteRoute:
    FgAuthenticatedFgArchiveBossRouteRouteWithChildren,
  FgAuthenticatedFgProfileRoute: FgAuthenticatedFgProfileRoute,
  FgAuthenticatedFgUploadRoute: FgAuthenticatedFgUploadRoute,
  FgAuthenticatedFgIndexRoute: FgAuthenticatedFgIndexRoute,
  FgAuthenticatedFgProjectsIndexRoute: FgAuthenticatedFgProjectsIndexRoute,
  FgAuthenticatedFgProjectsKull26FirstgameRoute:
    FgAuthenticatedFgProjectsKull26FirstgameRoute,
  FgAuthenticatedFgProjectsKull26SecondgameRoute:
    FgAuthenticatedFgProjectsKull26SecondgameRoute,
  FgAuthenticatedFgProjectsKull26ThirdgameRoute:
    FgAuthenticatedFgProjectsKull26ThirdgameRoute,
  FgAuthenticatedFgProjectsKull26IndexRoute:
    FgAuthenticatedFgProjectsKull26IndexRoute,
}

const FgAuthenticatedRouteRouteWithChildren =
  FgAuthenticatedRouteRoute._addFileChildren(FgAuthenticatedRouteRouteChildren)

interface OmOssRouteRouteChildren {
  OmOssBestillingRoute: typeof OmOssBestillingRoute
  OmOssBrukAvBilderRoute: typeof OmOssBrukAvBilderRoute
  OmOssIndexRoute: typeof OmOssIndexRoute
}

const OmOssRouteRouteChildren: OmOssRouteRouteChildren = {
  OmOssBestillingRoute: OmOssBestillingRoute,
  OmOssBrukAvBilderRoute: OmOssBrukAvBilderRoute,
  OmOssIndexRoute: OmOssIndexRoute,
}

const OmOssRouteRouteWithChildren = OmOssRouteRoute._addFileChildren(
  OmOssRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FgAuthenticatedRouteRoute: FgAuthenticatedRouteRouteWithChildren,
  OmOssRouteRoute: OmOssRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  MotiveMotiveIdRoute: MotiveMotiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
