name: get-env-variables

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the project
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }} # This makes the secret available
        run: npm run build

      - name: Get env variables
        run: echo "Getting env variables"
